### ISSUE TITLE
是否有继续完善编辑Demo这一块的计划

### ISSUE THREAD

**Issue by WS-Vincent** [ruanjx/VideoLab#22]

**Comment by kayyyuan** [comment]
编辑Demo目前只完成了主流程的逻辑，其余功能（贴纸、文字、滤镜、动画等）预计下半年更新。有任何相关的问题可以随时发邮件（kayyyuan@gmail.com），或者提issues，希望可以帮到您

**Comment by Chenggd** [comment]
什么时候完善更新呀，库非常好。
