### ISSUE TITLE
Can't add an audio-only layer

### ISSUE THREAD

**Issue by devoln** [ruanjx/VideoLab#4]
I have a RenderComposition with a video RenderLayer. I want to mix an audio file with this video.
I tried to create another RenderLayer with an AVAsset created from an AAC file and add it to my RenderComposition. After that, I could hear two audio streams from my video and audio files together, but the image disappeared. I got a black screen instead of my video.
Also, the length of the resulting video equals the length of the AAC file, even though I set a shorter CMTimeRange.

So, how do I accomplish this? Is this supported by VideoLab? If not, will it be supported and how can I work around this problem now?

**Comment by devoln** [comment]
I found this problem. It was probably my bug, I had a mismatch in source and layer durations. After I fixed it, everything is working correctly.

**Comment by Coder-ACJHP** [comment]
Hi @devoln 
I also facing same issue, I've tried a lot of things but either I got black screen or no audio.
How do you add only audio can you share sample code here please?
Thanks in advice

**Comment by devoln** [comment]
Hi @Coder-ACJHP
Unfortunately, I don't have simple sample code separate from my project which is NDA.

My issue wasn't related to audio because it reproduced with a video file too.

The bug was fixed when I made all `CMTimeRange` fields in the layer and its source were set to have the same duration value.

**Comment by Coder-ACJHP** [comment]
> Hi @Coder-ACJHP Unfortunately, I don't have simple sample code separate from my project which is NDA.
> 
> My issue wasn't related to audio because it reproduced with a video file too.
> 
> The bug was fixed when I made all `CMTimeRange` fields in the layer and its source were set to have the same duration value.

Thank you for quick reply, i got it  👍🏻
